<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Interfaces</name>
   <tag></tag>
   <elementGuidId>c5fdd80b-03b6-40fa-84ca-8870452dfc1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#class-summary-tab1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='class-summary-tab1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e28df191-d2bb-4188-bf30-035028144dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>class-summary-tab1</value>
      <webElementGuid>ff0bd6a9-4a92-48c9-853f-02a5bd2e0146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>38735a71-a5fe-4bb3-93a6-100f48b67f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ae0d9252-ab2a-4936-80ed-3d3832a87a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>class-summary.tabpanel</value>
      <webElementGuid>72f019e9-66f9-4d89-9498-8dfb364e7e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>61d1c219-eada-433d-9ca2-f355f46a4689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>switchTab(event)</value>
      <webElementGuid>465144ee-9e6a-49cd-b386-ec70706fc70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show('class-summary', 'class-summary-tab1', 2)</value>
      <webElementGuid>f3ae9a98-f82b-41aa-9ae8-668cafce1ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-tab</value>
      <webElementGuid>16b94a05-7aaf-4c57-9506-95f161dffe43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Interfaces</value>
      <webElementGuid>75d02f69-dfb4-40ac-ab3a-738cb897bbda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-summary-tab1&quot;)</value>
      <webElementGuid>42593d6a-b68f-4a1b-82c7-26eb29d1f7e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='class-summary-tab1']</value>
      <webElementGuid>9fd13253-6b57-48bb-a867-f78460828ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='class-summary']/div/button[2]</value>
      <webElementGuid>d840f48b-9459-4744-8125-ba53c1cf3136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Classes and Interfaces'])[1]/following::button[1]</value>
      <webElementGuid>06a3dce0-73bd-4138-9504-31953832242b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium'])[2]/following::button[2]</value>
      <webElementGuid>a49308dc-fedf-4ce7-b8f1-466f5fb6dd1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classes'])[1]/preceding::button[1]</value>
      <webElementGuid>6addc9f9-7b74-401c-8162-7b0f859c4364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enum Classes'])[1]/preceding::button[2]</value>
      <webElementGuid>e142f7a2-8aac-4a25-b671-ee7e074b5a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Interfaces']/parent::*</value>
      <webElementGuid>6cf5e402-99a4-4400-bff6-ff9c0ae75382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>fd13628e-dea6-4c1f-a86e-14a80e3a4cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'class-summary-tab1' and (text() = 'Interfaces' or . = 'Interfaces')]</value>
      <webElementGuid>111ea9bb-7770-4835-87b3-f8e642c9bba2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
